name: test

on: [push, pull_request]

jobs:

  windows:

    runs-on: windows-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, pypy-3.7]

    defaults:
      run:
        shell: bash

    steps:

    - name: Checkout pygraphviz
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set environment variables
      run: |
        URI='https://www2.graphviz.org/Packages/stable/portable_source/graphviz-2.44.1.tar.gz'
        echo "URI=$URI" >> $GITHUB_ENV
        echo "SRC=/C/graphviz-2.44.1.tar.gz" >> $GITHUB_ENV
        echo "ROOT=/C/graphviz-2.44.1" >> $GITHUB_ENV

    - name: Read exported variable
      run: |
        echo "$URI"
        echo "${{ env.URI }}"
        mkdir "${{ env.ROOT }}"
        ls "${{ env.ROOT }}"

    - name: Download graphviz source
      run: curl "${{ env.URI }}" -o "${{ env.SRC }}"

    - name: Unpack graphviz source
      run: tar xzf "${{ env.SRC }}" -C "${{ env.ROOT }}" --strip-components 1

    - name: List
      run: ls "${{ env.ROOT }}"

    - name: Configure
      run: |
        cd ${{ env.ROOT }}
        ./configure -C --without-gdk-pixbuf --with-mylibgd --disable-swig --without-x  --disable-tcl --without-ipsepcola --enable-shared --disable-static --enable-ltdl --without-gtk --without-gtkg

    - name: Make
      run: |
        cd ${{ env.ROOT }}
        make

    - name: Install
      run: |
        cd ${{ env.ROOT }}
        make install
